name: CraftierCards
favicon: null
layout_spectrum: 0.4139785
typography_spectrum: 0.07225
title: Craftier Cards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3955424
  lightness: 0.7222222
  saturation: 0.3172043
  rhythmicContrast: 0.9433013
purpose: []
